// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5JgMZSDlyvUYXfd4oapKpkrQzZb_9UnQ',
    appId: '1:230473503843:web:d55d044b5997f5b6e19456',
    messagingSenderId: '230473503843',
    projectId: 'wearproj-980b4',
    authDomain: 'wearproj-980b4.firebaseapp.com',
    storageBucket: 'wearproj-980b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDT_X_rpjBNMiazVGV2-4lFuaHbYM6AKg',
    appId: '1:230473503843:android:6c8cb1be06dcfd3ee19456',
    messagingSenderId: '230473503843',
    projectId: 'wearproj-980b4',
    storageBucket: 'wearproj-980b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwh3sqXbyBkfNPt9AjrdyIFz_jl1zSepo',
    appId: '1:230473503843:ios:1778e19d15647007e19456',
    messagingSenderId: '230473503843',
    projectId: 'wearproj-980b4',
    storageBucket: 'wearproj-980b4.appspot.com',
    iosClientId: '230473503843-pei44si8hfgj9n3ht30hp875cjlbiqbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.wearprojs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwh3sqXbyBkfNPt9AjrdyIFz_jl1zSepo',
    appId: '1:230473503843:ios:1778e19d15647007e19456',
    messagingSenderId: '230473503843',
    projectId: 'wearproj-980b4',
    storageBucket: 'wearproj-980b4.appspot.com',
    iosClientId: '230473503843-pei44si8hfgj9n3ht30hp875cjlbiqbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.wearprojs',
  );
}
